pipeline {
agent none
  stages {
    stage('Unit Tests - Backend') {

    agent {
      docker {
        image 'snakee/golang-junit:1.21'
        reuseNode true
        /* 
        Here /tmp is world-writable by default in most images, so this avoids 
        the permission issue without relying on the workspace path
        */
        args '-e GOCACHE=/tmp/.cache/go-build -e GOPATH=/tmp/go'
      }
    }
      steps {
        dir('bugtracker-backend') {
          sh 'go test -v ./...'
          }
        }
      }

     stage('Unit Tests - Frontend') {
      agent {
        docker {
          image 'node:26-alpine'
          reuseNode true
        }
      }

      steps {
        dir('bugtracker-frontend') {
          sh '''
            npm ci
            npm test
            '''
          }
        }
      }   

  }

}

